package pl.edu.agh.iosr.cloud.common.interfaces;

/**
 * Class should be used as common root for all classes responsible for connectivity between application and cloud
 * providers.
 *
 * Created by Krzysztof Kicinger on 2015-04-09.
 */
public abstract class ICloudConfiguration {

    /**
     * Method provides registered application name, required for OAuth2 application authorization.
     *
     * @return OAuth2 registered application name
     */
    protected abstract String getAppName();

    /**
     * Method is responsible for returning application key (Client ID/Key), generated by provider. Required
     * for OAuth2 application authorization.
     *
     * @return Application Key generated by provider.
     */
    protected abstract String getAppKey();

    /**
     * Method is responsible for returning application secret key (Client Secret), generated by provider. Required
     * for OAuth2 application authorization.
     *
     * @return Application Secret Key generated by provider.
     */
    protected abstract String getAppKeySecret();

}
